version: "1"
services:
    judge_server:
        image: judger_server_test
        read_only: true
        cap_drop:
            - SETPCAP
            - MKNOD
            - NET_BIND_SERVICE
            - SYS_CHROOT
            - SETFCAP
            - FSETID
        tmpfs:
            - /tmp
        volumes:
            - $PWD/sandbox:/sandbox
        environment:
            - SERVICE_URL=http://judge-server:9132
        ports:
            - "0.0.0.0:9132:8000"
